theme: jekyll-theme-hacker
title: Welcome to my page!
description: Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac?
- George Carlin
